on:
  pull_request:
  push:
    branches:
      - master

name: CI

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt --all --check
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo test
